# Defines project name
name: SatoshiFund Backend

services:
  api:
    # The image name is built dynamically from environment variables, with defaults for local development
    image: ${DOCKER_USER:-adriangcodes}/satoshifund-backend:${IMAGE_TAG:-v1.0.0-${NODE_ENV:-development}}
    build: .
    container_name: satoshifund-api
    restart: unless-stopped
    depends_on:
    - mongo
    # Set environment variables - to be overridden in CI/CD by GitHub Actions secrets
    environment:
      - MONGODB_URI=mongodb://mongo:27017/satoshifunddb-${NODE_ENV:-development}
      - NODE_ENV=${NODE_ENV:-development}
      # Following variables are securely sourced from .env
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
    - "8080:8080"
    networks:
    - satoshifund-net
  
  mongo:
    image: mongo:latest
    container_name: satoshifund-mongo
    restart: unless-stopped
    volumes:
    - satoshifund-data:/data/db
    ports:
    - "27017:27017"
    networks:
    - satoshifund-net

# Defines volume for persistent MongoDB data
volumes:
  satoshifund-data:
    driver: local

# Defines network that allows services to communicate
networks:
  satoshifund-net:
    driver: bridge