name: CI - Development

on:
  # Trigger on push to development branches
  push:
    branches:
      - 'main'
      - 'feat/*'
  
  # Manual trigger for testing
  workflow_dispatch:

jobs:
  # Use the reusable setup workflow
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      node-version: '22'
      mongodb-version: '7.0'
      install-dependencies: true
      setup-mongodb: true

  # Quick test job - leverages the setup from previous job
  quick-test:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with cache
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run quick test suite
        env:
          MONGODB_URI: mongodb://localhost:27017/test-db
          NODE_ENV: test
          JWT_SECRET: test-secret
        run: |
          echo "Running quick test suite..."
          npm test -- --maxWorkers=2 --silent

      - name: Summary
        if: always()
        run: |
          echo "## Development CI Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY